[package]
name = "mbimap"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/fawdlstty/mbimap"
homepage = "https://github.com/fawdlstty/mbimap"
description = "Pooled bijective maps in Rust"
authors = ["fawdlstty<f@fawdlstty.com>"]
keywords = ["bimap", "pool"]
categories = []
readme = "README.md"

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = ["serialize"]
serialize = ["dep:serde"]

# cargo publish --allow-dirty --registry crates-io
